"%prod":
  kafka:
    bootstrap:
      servers: "kafka:9092"

"%test":
  quarkus:
    hibernate-orm:
      database:
        generation: "drop-and-create"
    datasource:
      db-kind: "sqlite"
      username: "template"
      password: "secret"
      jdbc:
        url: "jdbc:sqlite:test.db"

quarkus:
  http:
    port: 8081
  swagger-ui:
    always-include: true
  kafka:
    devservices:
      topic-partitions:
        product: 1
        offering: 1
  hibernate-orm:
    database:
      generation: "update"
  datasource:
    db-kind: "sqlite"
    username: "template"
    password: "secret"
    jdbc:
      url: "jdbc:sqlite:database.db"

kafka:
  auto:
    offset:
      reset: "earliest"

mp:
  messaging:
    outgoing:
      offering-out:
        topic: "offering"
    incoming:
      product-in:
        topic: "product"
